### ISSUE TITLE
Maintaining under Moleculer org

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer-io#41]
Hi @tiaod,

are you still maintaining this repo? If not, could you transfer the repo into the moleculerjs organization on Github, and transfer the NPM access to me?

Thanks, in advance!

**Comment by tiaod** [comment]
I have been writing client programs in my recent work, and I haven't written server code for a long time, so I haven't used moleculerjs for a while, and this project is currently not being maintained. I will transfer it to you.

**Comment by tiaod** [comment]
@icebob You should first give me permission to create repositories in moleculerjs organization

**Comment by icebob** [comment]
I've sent an invite.

**Comment by tiaod** [comment]
Done!

**Comment by icebob** [comment]
Awesome, thanks!
